version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: node:8.0
    user: "node"
    working_dir: /home/node/app
   # environment:
    #  - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "yarn dev"
